# Generated by Django 3.0.8 on 2020-09-04 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('info_by', models.CharField(blank=True, max_length=60, verbose_name='Source (Person Name)')),
                ('company_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('EC', 'Exam/Competition'), ('FT', 'Full Time Job'), ('IT', 'Internship')], max_length=2)),
                ('desc_url', models.URLField(verbose_name='Description URL')),
                ('appln_url', models.URLField(verbose_name='Application URL')),
                ('deadline', models.DateField()),
                ('platform', models.CharField(choices=[('OTHR', 'Others'), ('YOUT', 'YouTube'), ('LNKD', 'LinkedIn'), ('INTS', 'Internshala'), ('CMPY', 'Company Page')], max_length=4)),
                ('remarks', models.TextField(default='No Remarks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
