# Generated by Django 3.0.8 on 2020-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('IT', 'Internship'), ('FT', 'Full Time Job'), ('EC', 'Exam/Competition')], max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='platform',
            field=models.CharField(choices=[('INTS', 'Internshala'), ('OTHR', 'Others'), ('YOUT', 'YouTube'), ('CMPY', 'Company Page'), ('LNKD', 'LinkedIn')], max_length=4),
        ),
    ]
