# Generated by Django 3.0.8 on 2020-09-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200905_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full Time Job'), ('IT', 'Internship'), ('EC', 'Exam/Competition')], max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='platform',
            field=models.CharField(choices=[('LNKD', 'LinkedIn'), ('YOUT', 'YouTube'), ('INTS', 'Internshala'), ('CMPY', 'Company Page'), ('OTHR', 'Others')], max_length=4),
        ),
    ]
